In [1]:
import osmnx as ox

print(ox.__version__)

2.1.1

In [ ]:
# 다운받을 지도의 중심
center = (37.5665, 126.9780)

# 데이터 다운로드 하기
G = ox.graph.graph_from_point(
  center_point=center,
  dist=1000, # km
  network_type="walk" # 도로망 형식
)

print(G)

MultiDiGraph with 1913 nodes and 5302 edges

In [ ]:
# G.node 출력해보기
# 내부에 들어있는 정보를 볼 수 있다.
for node_id, data in list(G.nodes(data=True))[:5]:
  print(node_id)
  print(data)
  print()

287631232
{'y': 37.5700513, 'x': 126.972549, 'street_count': 4}

287712142
{'y': 37.5740414, 'x': 126.9726915, 'street_count': 4}

287712330
{'y': 37.5701892, 'x': 126.9725486, 'street_count': 4}

292395181
{'y': 37.5733209, 'x': 126.985911, 'street_count': 3}

292395190
{'y': 37.5729775, 'x': 126.9862331, 'street_count': 4}

for u, v, key, data in list(G.edges(keys=True, data=True))[:5]:
    print("출발:", u)
    print("도착:", v)
    print(data)
    print()

In [ ]:
# edge 데이터 출력해보기
# 데이터도 함께 받았을 때 시작/종료 노드와 그 두 노드를 잇는 key(인덱스)
# 그리고 data값이 나오는 것을 알 수 있다.
# 퀄리티가 꽤 좋다.
for u, v, key, data in list(G.edges(keys=True, data=True))[:5]:
    print("출발:", u)
    print("도착:", v)
    print(data)
    print()

출발: 287631232
도착: 1936511583
{'osmid': 919985574, 'highway': 'primary', 'lanes': '4', 'maxspeed': '60', 'name': '새문안로', 'oneway': False, 'ref': '6', 'reversed': False, 'length': np.float64(168.02524123507987)}

출발: 287631232
도착: 11270546915
{'osmid': 180793307, 'highway': 'residential', 'name': '새문안로', 'oneway': False, 'reversed': True, 'length': np.float64(69.99775968479476), 'geometry': <LINESTRING (126.973 37.57, 126.973 37.57, 126.973 37.569)>}

출발: 287631232
도착: 5863307785
{'osmid': 621513156, 'highway': 'primary', 'lanes': '4', 'maxspeed': '60', 'name': '새문안로', 'oneway': False, 'ref': '6', 'reversed': True, 'length': np.float64(93.59036339692808), 'geometry': <LINESTRING (126.973 37.57, 126.972 37.57, 126.972 37.57, 126.972 37.57)>}

출발: 287631232
도착: 287712330
{'osmid': 919985573, 'highway': 'residential', 'name': '새문안로3길', 'oneway': False, 'reversed': False, 'length': np.float64(15.33385320082875), 'geometry': <LINESTRING (126.973 37.57, 126.973 37.57, 126.973 37.57, 126.973 37.57, 126...>}

출발: 287712142
도착: 436807109
{'osmid': 37399752, 'highway': 'tertiary', 'lanes': '4', 'name': '사직로8길', 'oneway': False, 'reversed': False, 'length': np.float64(65.80381653522515)}

In [ ]:
# 행렬로 데이터 출력해보기
nodes, edges = ox.convert.graph_to_gdfs(G)

# 노드 데이터들 DF
nodes.head()

,y,x,street_count,junction,highway,railway,ref,geometry
osmid,,,,,,,,
287631232,37.570051,126.972549,4,NaN,NaN,NaN,NaN,POINT (126.97255 37.57005)
287712142,37.574041,126.972691,4,NaN,NaN,NaN,NaN,POINT (126.97269 37.57404)
287712330,37.570189,126.972549,4,NaN,NaN,NaN,NaN,POINT (126.97255 37.57019)
292395181,37.573321,126.985911,3,NaN,NaN,NaN,NaN,POINT (126.98591 37.57332)
292395190,37.572978,126.986233,4,NaN,NaN,NaN,NaN,POINT (126.98623 37.57298)

In [9]:
# 거리 데이터 행렬
edges.head()

                               osmid      highway lanes maxspeed    name  \
u         v           key
287631232 1936511583  0    919985574      primary     4       60    새문안로
          11270546915 0    180793307  residential   NaN      NaN    새문안로
          5863307785  0    621513156      primary     4       60    새문안로
          287712330   0    919985573  residential   NaN      NaN  새문안로3길
287712142 436807109   0     37399752     tertiary     4      NaN   사직로8길

                           oneway  ref reversed      length  \
u         v           key
287631232 1936511583  0     False    6    False  168.025241
          11270546915 0     False  NaN     True   69.997760
          5863307785  0     False    6     True   93.590363
          287712330   0     False  NaN    False   15.333853
287712142 436807109   0     False  NaN    False   65.803817

                                                                    geometry  \
u         v           key
287631232 1936511583  0    LINESTRING (126.97255 37.57005, 126.97446 37.5...
          11270546915 0    LINESTRING (126.97255 37.57005, 126.97267 37.5...
          5863307785  0    LINESTRING (126.97255 37.57005, 126.97213 37.5...
          287712330   0    LINESTRING (126.97255 37.57005, 126.97255 37.5...
287712142 436807109   0    LINESTRING (126.97269 37.57404, 126.97344 37.5...

                          access service junction bridge tunnel width
u         v           key
287631232 1936511583  0      NaN     NaN      NaN    NaN    NaN   NaN
          11270546915 0      NaN     NaN      NaN    NaN    NaN   NaN
          5863307785  0      NaN     NaN      NaN    NaN    NaN   NaN
          287712330   0      NaN     NaN      NaN    NaN    NaN   NaN
287712142 436807109   0      NaN     NaN      NaN    NaN    NaN   NaN

In [11]:
# 공원 데이터 받아오기
parks = ox.features.features_from_point(
    center_point=center,
    tags={
        "leisure": "park" # 태그를 이용해서 원하는 피처 가져오기
    },
    dist=1000 # 1000m 반경 가져오기
)

print(parks.columns)
parks.head()

Index(['geometry', 'leisure', 'name', 'name:ko', 'name:ja', 'name:zh',
       'addr:city', 'addr:district', 'addr:housenumber', 'addr:postcode',
       'addr:street', 'addr:subdistrict', 'name:en', 'phone', 'website',
       'name:zh-Hans', 'name:zh-Hant', 'landuse', 'wikidata', 'wikipedia:en',
       'operator', 'type', 'tourism', 'website:en', 'website:ko', 'wikipedia',
       'name:ru', 'wheelchair'],
      dtype='str')

                                                               geometry  \
element  id
node     12069181104                          POINT (126.98032 37.5694)
         13985578601                         POINT (126.97457 37.57241)
relation 10739781     POLYGON ((126.98257 37.57423, 126.98246 37.574...
         10754626     POLYGON ((126.97274 37.56679, 126.97271 37.566...
         10773547     POLYGON ((126.97022 37.55967, 126.96948 37.559...

                     leisure       name      name:ko  name:ja  name:zh  \
element  id
node     12069181104    park  청계천이보이는쉼터  청계천이 보이는 쉼터      NaN      NaN
         13985578601    park        NaN          NaN      NaN      NaN
relation 10739781       park   우정총국시민광장     우정총국시민광장      NaN      NaN
         10754626       park        중명전          NaN      NaN      NaN
         10773547       park    서소문근린공원      서소문근린공원  西小門近隣公園  西小门近邻公园

                     addr:city addr:district addr:housenumber addr:postcode  \
element  id
node     12069181104       NaN           NaN              NaN           NaN
         13985578601       NaN           NaN              NaN           NaN
relation 10739781        서울특별시           종로구               59         03144
         10754626          NaN           NaN              NaN           NaN
         10773547          NaN           NaN              NaN           NaN

                      ... wikidata wikipedia:en operator          type  \
element  id           ...
node     12069181104  ...      NaN          NaN      NaN           NaN
         13985578601  ...      NaN          NaN      NaN           NaN
relation 10739781     ...      NaN          NaN      NaN  multipolygon
         10754626     ...      NaN          NaN      NaN  multipolygon
         10773547     ...      NaN          NaN      NaN  multipolygon

                     tourism website:en website:ko wikipedia name:ru  \
element  id
node     12069181104     NaN        NaN        NaN       NaN     NaN
         13985578601     NaN        NaN        NaN       NaN     NaN
relation 10739781        NaN        NaN        NaN       NaN     NaN
         10754626        NaN        NaN        NaN       NaN     NaN
         10773547        NaN        NaN        NaN       NaN     NaN

                     wheelchair
element  id
node     12069181104        NaN
         13985578601        NaN
relation 10739781           NaN
         10754626           NaN
         10773547           NaN

[5 rows x 28 columns]

In [12]:
ox.io.save_graph_geopackage(
    G,
    filepath="seoul_walk.gpkg"
)